//
// Created by Daniil on 12.04.2022.
//

#ifndef PROGRAMMING_OF_DYNAMIC_DATA_STRUCTURES_SETLAB5_H
#define PROGRAMMING_OF_DYNAMIC_DATA_STRUCTURES_SETLAB5_H


class SetLab5 {

};


#endif //PROGRAMMING_OF_DYNAMIC_DATA_STRUCTURES_SETLAB5_H
