//
// Created by Daniil on 12.04.2022.
//

#ifndef PROGRAMMING_OF_DYNAMIC_DATA_STRUCTURES_SETLABQUEUE_H
#define PROGRAMMING_OF_DYNAMIC_DATA_STRUCTURES_SETLABQUEUE_H


class SetLabQueue {

};


#endif //PROGRAMMING_OF_DYNAMIC_DATA_STRUCTURES_SETLABQUEUE_H
